#!/usr/bin/env python3
"""Scan avatar/wing artwork and write normalized content boxes.

Re-run this whenever artwork is added or replaced:
    python artifacts/artifacts/mobile/scripts/measure-asset-bounds.py
"""
from __future__ import annotations

import os
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "constants" / "assetContentBounds.ts"

AVATARS = {
    "avatar_1": ROOT / "assets" / "avatar" / "Abigail.webp",
    "avatar_2": ROOT / "assets" / "avatar" / "chloe.webp",
    "avatar_3": ROOT / "assets" / "avatar" / "Daveigh.webp",
    "avatar_4": ROOT / "assets" / "avatar" / "Haley.webp",
    "avatar_5": ROOT / "assets" / "avatar" / "Heather.webp",
    "avatar_6": ROOT / "assets" / "avatar" / "kirsten.webp",
    "avatar_7": ROOT / "assets" / "avatar" / "Linda.webp",
    "avatar_8": ROOT / "assets" / "avatar" / "Marilyn.webp",
    "avatar_9": ROOT / "assets" / "avatar" / "Patty.webp",
    "avatar_10": ROOT / "assets" / "avatar" / "Sissy.webp",
}

WINGS = {
    "wing_basic": ROOT / "assets" / "wings" / "base-wings.png",
    "wing_feather": ROOT / "assets" / "wings" / "featur-wings.png",
    "wing_star": ROOT / "assets" / "wings" / "star-wings.png",
    "wing_shadow": ROOT / "assets" / "wings" / "shadow-wings.png",
    "wing_angel": ROOT / "assets" / "wings" / "angel-wings.png",
}


def is_padding(r: int, g: int, b: int, a: int) -> bool:
    if a < 12:
        return True
    # Solid black / white studio backdrops are not part of the figure.
    if r <= 18 and g <= 18 and b <= 18:
        return True
    if r >= 248 and g >= 248 and b >= 248:
        return True
    return False


def measure(path: Path) -> dict:
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    px = im.load()
    minx, miny, maxx, maxy = w, h, -1, -1
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if is_padding(r, g, b, a):
                continue
            if x < minx:
                minx = x
            if y < miny:
                miny = y
            if x > maxx:
                maxx = x
            if y > maxy:
                maxy = y
    if maxx < 0:
        minx, miny, maxx, maxy = 0, 0, w - 1, h - 1
    return {
        "canvasW": w,
        "canvasH": h,
        "left": round(minx / w, 4),
        "top": round(miny / h, 4),
        "right": round((maxx + 1) / w, 4),
        "bottom": round((maxy + 1) / h, 4),
    }


def emit(id_: str, m: dict) -> str:
    return (
        f'  {id_}: {{ canvasW: {m["canvasW"]}, canvasH: {m["canvasH"]}, '
        f'left: {m["left"]}, top: {m["top"]}, right: {m["right"]}, bottom: {m["bottom"]} }},'
    )


def main() -> None:
    os.chdir(ROOT)
    lines = [
        "/** Auto-generated by scripts/measure-asset-bounds.py — do not hand-edit. */",
        "export interface AssetContentBounds {",
        "  canvasW: number;",
        "  canvasH: number;",
        "  left: number;",
        "  top: number;",
        "  right: number;",
        "  bottom: number;",
        "}",
        "",
        "export const ASSET_CONTENT_BOUNDS: Record<string, AssetContentBounds> = {",
    ]
    for key, path in {**AVATARS, **WINGS}.items():
        lines.append(emit(key, measure(path)))
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
