/** Auto-generated by scripts/measure-asset-bounds.py — do not hand-edit. */
export interface AssetContentBounds {
  canvasW: number;
  canvasH: number;
  left: number;
  top: number;
  right: number;
  bottom: number;
}

export const ASSET_CONTENT_BOUNDS: Record<string, AssetContentBounds> = {
  avatar_1: { canvasW: 1080, canvasH: 1620, left: 0.1435, top: 0.0735, right: 0.8602, bottom: 0.9346 },
  avatar_2: { canvasW: 1080, canvasH: 1350, left: 0.2519, top: 0.0763, right: 0.7556, bottom: 0.9585 },
  avatar_3: { canvasW: 1080, canvasH: 1620, left: 0.2389, top: 0.0864, right: 0.6981, bottom: 0.9451 },
  avatar_4: { canvasW: 1080, canvasH: 1920, left: 0.2806, top: 0.0625, right: 0.7491, bottom: 0.949 },
  avatar_5: { canvasW: 1080, canvasH: 1620, left: 0.25, top: 0.0765, right: 0.8028, bottom: 0.9259 },
  avatar_6: { canvasW: 1080, canvasH: 1620, left: 0.2648, top: 0.1327, right: 0.6852, bottom: 0.8957 },
  avatar_7: { canvasW: 1080, canvasH: 1660, left: 0.137, top: 0.0, right: 0.8685, bottom: 0.9747 },
  avatar_8: { canvasW: 1080, canvasH: 1920, left: 0.2194, top: 0.0422, right: 0.7833, bottom: 0.9521 },
  avatar_9: { canvasW: 1080, canvasH: 1920, left: 0.1907, top: 0.0833, right: 0.8361, bottom: 0.9422 },
  avatar_10: { canvasW: 1080, canvasH: 1389, left: 0.0907, top: 0.0245, right: 0.9731, bottom: 0.9834 },
  wing_basic: { canvasW: 550, canvasH: 557, left: 0.0655, top: 0.1382, right: 0.9418, bottom: 0.939 },
  wing_feather: { canvasW: 518, canvasH: 386, left: 0.0965, top: 0.1244, right: 0.9015, bottom: 0.8756 },
  wing_star: { canvasW: 588, canvasH: 420, left: 0.1003, top: 0.1667, right: 0.8997, bottom: 0.731 },
  wing_shadow: { canvasW: 2500, canvasH: 2500, left: 0.0792, top: 0.0248, right: 0.9204, bottom: 0.9208 },
  wing_angel: { canvasW: 554, canvasH: 554, left: 0.0866, top: 0.1552, right: 0.9007, bottom: 0.8538 },
};
