import { z } from "zod";
import { logger } from "../../lib/logger";
import { HttpError } from "./errors";
import { extractJson } from "./prompts";
import { createOpenAiTextProvider } from "./providers/text/openai";
import { SPEED_CARD_COUNT, SPEED_CARD_IDS, SPEED_CARD_PALETTE, swatchById } from "./speedCardPalette";
import type { Difficulty } from "./types";

/** Existing 16-id palette, grouped so Easy/Hard rounds are mechanically different. */
const DIFFICULTY_POOL: Record<Difficulty, readonly string[]> = {
  easy: ["red", "blue", "yellow", "green", "orange", "black", "white", "purple"],
  medium: SPEED_CARD_IDS,
  hard: ["blue", "navy", "turquoise", "green", "lime", "gold", "yellow", "pink", "magenta", "gray"],
};

const RoundSchema = z.object({
  colors: z.array(z.string()).length(SPEED_CARD_COUNT),
  questions: z.array(z.string()).length(SPEED_CARD_COUNT),
});

const SYSTEM = `You generate one online Speed Card round. Reply with a single JSON object and nothing else.`;

export function parseSpeedCardDifficulty(value: unknown): Difficulty {
  if (value === "easy" || value === "medium" || value === "hard") return value;
  throw new HttpError(400, "difficulty must be easy, medium, or hard");
}

function buildUserPrompt(difficulty: Difficulty): string {
  const ids = shuffleInPlace([...DIFFICULTY_POOL[difficulty]]).join(", ");
  return `This Speed Card round is ${difficulty}. Pick ${SPEED_CARD_COUNT} distinct color ids from this shuffled palette: ${ids}.

Return JSON of the exact shape:
{"colors":[string,string,string,string,string],"questions":[string,string,string,string,string]}

Rules:
- "colors": ${SPEED_CARD_COUNT} unique ids from the palette. No repeats.
- "questions": the same ${SPEED_CARD_COUNT} ids as "colors", in a different random order. No repeats. No extra ids.
- Use only palette ids. Do not invent names.
- Do not prefer ids that appear earlier in the list.`;
}

function isPermutation(colors: string[], questions: string[]): boolean {
  if (colors.length !== questions.length) return false;
  const a = [...colors].sort();
  const b = [...questions].sort();
  return a.every((id, i) => id === b[i]);
}

function uniqueAllowed(ids: string[], difficulty: Difficulty): boolean {
  const pool = new Set(DIFFICULTY_POOL[difficulty]);
  const set = new Set(ids);
  if (set.size !== ids.length) return false;
  return ids.every((id) => pool.has(id));
}

export interface SpeedCardRound {
  colors: { id: string; name: string; hex: string }[];
  questions: { id: string; name: string; hex: string }[];
}

function shuffleInPlace<T>(items: T[]): T[] {
  for (let i = items.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    const current = items[i];
    const swap = items[j];
    if (current === undefined || swap === undefined) continue;
    items[i] = swap;
    items[j] = current;
  }
  return items;
}

function hydrate(ids: string[]): SpeedCardRound["colors"] {
  return ids.map((id) => {
    const swatch = swatchById(id);
    if (!swatch) throw new Error(`Unknown color id ${id}`);
    return swatch;
  });
}

export function buildSpeedCardRoundFromPalette(difficulty: Difficulty = "medium"): SpeedCardRound {
  const pool = shuffleInPlace([...DIFFICULTY_POOL[difficulty]]);
  const colorIds = pool.slice(0, SPEED_CARD_COUNT);
  const questionIds = shuffleInPlace([...colorIds]);
  if (questionIds.length > 1 && questionIds.every((id, index) => id === colorIds[index])) {
    const first = questionIds.shift();
    if (first !== undefined) questionIds.push(first);
  }
  return {
    colors: hydrate(colorIds),
    questions: hydrate(questionIds),
  };
}

export async function generateSpeedCardRound(difficulty: Difficulty = "medium"): Promise<SpeedCardRound> {
  const openai = createOpenAiTextProvider();
  if (!openai.isConfigured()) {
    throw new HttpError(503, "OPENAI_API_KEY is not configured on the API server");
  }

  let lastMessage = "OpenAI Speed Card round failed";
  for (let attempt = 0; attempt < 2; attempt += 1) {
    try {
      const raw = await openai.complete({ system: SYSTEM, user: buildUserPrompt(difficulty) });
      const parsed = RoundSchema.parse(extractJson(raw));
      const colorIds = parsed.colors.map((id) => id.trim().toLowerCase());
      const questionIds = parsed.questions.map((id) => id.trim().toLowerCase());

      if (!uniqueAllowed(colorIds, difficulty) || !isPermutation(colorIds, questionIds)) {
        throw new Error("OpenAI returned an invalid Speed Card palette selection");
      }

      logger.info({ colors: colorIds, questions: questionIds, difficulty }, "Speed Card round generated by OpenAI");
      return {
        colors: hydrate(colorIds),
        questions: hydrate(questionIds),
      };
    } catch (err) {
      lastMessage = err instanceof Error ? err.message : lastMessage;
      logger.warn({ attempt, err, difficulty }, "Speed Card OpenAI attempt failed");
    }
  }

  throw new HttpError(502, lastMessage);
}

export function getSpeedCardPalette() {
  return SPEED_CARD_PALETTE;
}
