import { z } from "zod";
import { logger } from "../../lib/logger";
import { extractJson } from "./prompts";
import { createOpenAiTextProvider } from "./providers/text/openai";
import { SPEED_CARD_COUNT, SPEED_CARD_IDS, SPEED_CARD_PALETTE, swatchById } from "./speedCardPalette";
import type { Difficulty } from "./types";

const RoundSchema = z.object({
  colors: z.array(z.string()).length(SPEED_CARD_COUNT),
  questions: z.array(z.string()).length(SPEED_CARD_COUNT),
});

const SYSTEM = `You generate one online Speed Card round. Reply with a single JSON object and nothing else.`;

export function parseSpeedCardDifficulty(value: unknown): Difficulty {
  if (value === "easy" || value === "medium" || value === "hard") return value;
  return "medium";
}

function buildUserPrompt(difficulty: Difficulty): string {
  const ids = shuffleInPlace([...SPEED_CARD_IDS]).join(", ");
  return `This Speed Card round is ${difficulty}. Pick ${SPEED_CARD_COUNT} distinct color ids from this shuffled palette: ${ids}.

Return JSON of the exact shape:
{"colors":[string,string,string,string,string],"questions":[string,string,string,string,string]}

Rules:
- "colors": ${SPEED_CARD_COUNT} unique ids from the palette. No repeats.
- "questions": the same ${SPEED_CARD_COUNT} ids as "colors", in a different random order. No repeats. No extra ids.
- Use only palette ids. Do not invent names.
- Do not prefer ids that appear earlier in the list.`;
}

function isPermutation(colors: string[], questions: string[]): boolean {
  if (colors.length !== questions.length) return false;
  const a = [...colors].sort();
  const b = [...questions].sort();
  return a.every((id, i) => id === b[i]);
}

function uniqueAllowed(ids: string[]): boolean {
  const set = new Set(ids);
  if (set.size !== ids.length) return false;
  return ids.every((id) => SPEED_CARD_IDS.includes(id));
}

export interface SpeedCardRound {
  colors: { id: string; name: string; hex: string }[];
  questions: { id: string; name: string; hex: string }[];
}

function shuffleInPlace<T>(items: T[]): T[] {
  for (let i = items.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    const current = items[i];
    const swap = items[j];
    if (current === undefined || swap === undefined) continue;
    items[i] = swap;
    items[j] = current;
  }
  return items;
}

function hydrate(ids: string[]): SpeedCardRound["colors"] {
  return ids.map((id) => {
    const swatch = swatchById(id);
    if (!swatch) throw new Error(`Unknown color id ${id}`);
    return swatch;
  });
}

export function buildSpeedCardRoundFromPalette(): SpeedCardRound {
  const pool = shuffleInPlace([...SPEED_CARD_IDS]);
  const colorIds = pool.slice(0, SPEED_CARD_COUNT);
  const questionIds = shuffleInPlace([...colorIds]);
  if (questionIds.length > 1 && questionIds.every((id, index) => id === colorIds[index])) {
    const first = questionIds.shift();
    if (first !== undefined) questionIds.push(first);
  }
  return {
    colors: hydrate(colorIds),
    questions: hydrate(questionIds),
  };
}

export async function generateSpeedCardRound(difficulty: Difficulty = "medium"): Promise<SpeedCardRound> {
  const openai = createOpenAiTextProvider();
  if (openai.isConfigured()) {
    let lastMessage = "OpenAI Speed Card round failed";
    for (let attempt = 0; attempt < 2; attempt += 1) {
      try {
        const raw = await openai.complete({ system: SYSTEM, user: buildUserPrompt(difficulty) });
        const parsed = RoundSchema.parse(extractJson(raw));
        const colorIds = parsed.colors.map((id) => id.trim().toLowerCase());
        const questionIds = parsed.questions.map((id) => id.trim().toLowerCase());

        if (!uniqueAllowed(colorIds) || !isPermutation(colorIds, questionIds)) {
          throw new Error("OpenAI returned an invalid Speed Card palette selection");
        }

        logger.info({ colors: colorIds, questions: questionIds }, "Speed Card round generated by OpenAI");
        return {
          colors: hydrate(colorIds),
          questions: hydrate(questionIds),
        };
      } catch (err) {
        lastMessage = err instanceof Error ? err.message : lastMessage;
        logger.warn({ attempt, err }, "Speed Card OpenAI attempt failed");
      }
    }
    logger.warn({ lastMessage }, "Speed Card falling back to palette shuffle");
  }

  return buildSpeedCardRoundFromPalette();
}

export function getSpeedCardPalette() {
  return SPEED_CARD_PALETTE;
}
