import { z } from "zod";
import { logger } from "../../lib/logger";
import { HttpError } from "./errors";
import { extractJson } from "./prompts";
import { createOpenAiTextProvider } from "./providers/text/openai";
import { SPEED_CARD_COUNT, SPEED_CARD_IDS, SPEED_CARD_PALETTE, swatchById } from "./speedCardPalette";

const RoundSchema = z.object({
  colors: z.array(z.string()).length(SPEED_CARD_COUNT),
  questions: z.array(z.string()).length(SPEED_CARD_COUNT),
});

const SYSTEM = `You generate one online Speed Card round. Reply with a single JSON object and nothing else.`;

function buildUserPrompt(): string {
  const ids = SPEED_CARD_IDS.join(", ");
  return `Pick ${SPEED_CARD_COUNT} distinct color ids from this palette: ${ids}.

Return JSON of the exact shape:
{"colors":[string,string,string,string,string],"questions":[string,string,string,string,string]}

Rules:
- "colors": ${SPEED_CARD_COUNT} unique ids from the palette. No repeats.
- "questions": the same ${SPEED_CARD_COUNT} ids as "colors", in a different random order. No repeats. No extra ids.
- Use only palette ids. Do not invent names.`;
}

function isPermutation(colors: string[], questions: string[]): boolean {
  if (colors.length !== questions.length) return false;
  const a = [...colors].sort();
  const b = [...questions].sort();
  return a.every((id, i) => id === b[i]);
}

function uniqueAllowed(ids: string[]): boolean {
  const set = new Set(ids);
  if (set.size !== ids.length) return false;
  return ids.every((id) => SPEED_CARD_IDS.includes(id));
}

export interface SpeedCardRound {
  colors: { id: string; name: string; hex: string }[];
  questions: { id: string; name: string; hex: string }[];
}

export async function generateSpeedCardRound(): Promise<SpeedCardRound> {
  const openai = createOpenAiTextProvider();
  if (!openai.isConfigured()) {
    throw new HttpError(503, "OPENAI_API_KEY is not configured on the API server");
  }

  let lastMessage = "OpenAI Speed Card round failed";

  for (let attempt = 0; attempt < 2; attempt += 1) {
    try {
      const raw = await openai.complete({ system: SYSTEM, user: buildUserPrompt() });
      const parsed = RoundSchema.parse(extractJson(raw));
      const colorIds = parsed.colors.map((id) => id.trim().toLowerCase());
      const questionIds = parsed.questions.map((id) => id.trim().toLowerCase());

      if (!uniqueAllowed(colorIds) || !isPermutation(colorIds, questionIds)) {
        throw new Error("OpenAI returned an invalid Speed Card palette selection");
      }

      const colors = colorIds.map((id) => {
        const swatch = swatchById(id);
        if (!swatch) throw new Error(`Unknown color id ${id}`);
        return swatch;
      });
      const questions = questionIds.map((id) => {
        const swatch = swatchById(id);
        if (!swatch) throw new Error(`Unknown color id ${id}`);
        return swatch;
      });

      logger.info({ colors: colorIds, questions: questionIds }, "Speed Card round generated by OpenAI");
      return { colors, questions };
    } catch (err) {
      lastMessage = err instanceof Error ? err.message : lastMessage;
      logger.warn({ attempt, err }, "Speed Card OpenAI attempt failed");
    }
  }

  throw new HttpError(502, lastMessage);
}

export function getSpeedCardPalette() {
  return SPEED_CARD_PALETTE;
}
